import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Projects Page",
  description: "Generated by create next app",
};

export default function Projectsayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
