import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import { ReduxProvider } from "./Providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Ensure any client-specific behavior is handled inside useEffect or after hydration.
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <div className="flex max-sm:flex-col max-xl:flex-col max-lg:flex-col max-md:flex-col gap-5 ">
            <SideBar />
            <div className="p-10 max-sm:p-5 max-md:p-5 max-lg:p-5 relative">
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
